# Generated by Django 5.2 on 2025-11-07 06:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import geoclient.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StationDirectoryName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальное имя станции из справочника (например, Вахим, База_1)",
                        max_length=255,
                        unique=True,
                        verbose_name="Имя станции в справочнике",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления записи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись справочника имен",
                "verbose_name_plural": "Справочник имен станций",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UploadedRinexFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=geoclient.models.rinex_file_path, verbose_name="Файл"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Хэш-сумма SHA-256 содержимого файла для определения дубликатов.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время загрузки"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="Тип файла (o, n, g, и т.д.)",
                        max_length=10,
                        null=True,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Заметки или комментарии по файлу",
                        null=True,
                        verbose_name="Заметки",
                    ),
                ),
                (
                    "upload_group",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Уникальный идентификатор для группы связанных файлов (например, .o, .g, .n)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Загруженный RINEX файл",
                "verbose_name_plural": "Загруженные RINEX файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GeodeticPoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Уникальный ID пункта (Marker Name из RINEX)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID пункта",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Присвоенное имя станции",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Актуальное местоположение"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("ggs", "Пункты гос. геодезической сети"),
                            ("ggs_kurgan", "Пункты ГГС на курганах"),
                            ("survey", "Точки съемочной сети"),
                            ("survey_kurgan", "Точки съемочной сети на курганах"),
                            ("astro", "Астрономические пункты"),
                            ("leveling", "Нивелирные марки/реперы"),
                            ("default", "Неопределенный тип"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="Тип точки",
                    ),
                ),
                (
                    "network_class",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Класс сети"
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Индекс (номенклатура)",
                    ),
                ),
                (
                    "center_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Тип центра"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Статус"
                    ),
                ),
                (
                    "mark_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер марки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления записи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Геодезический пункт",
                "verbose_name_plural": "Геодезические пункты",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["location"], name="geopoint_location_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Местоположение наблюдения"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(verbose_name="Время наблюдения (первого)"),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Длительность наблюдения"
                    ),
                ),
                (
                    "raw_x",
                    models.FloatField(
                        blank=True,
                        help_text="Исходная координата X (ECEF из RINEX)",
                        null=True,
                    ),
                ),
                (
                    "raw_y",
                    models.FloatField(
                        blank=True,
                        help_text="Исходная координата Y (ECEF из RINEX)",
                        null=True,
                    ),
                ),
                (
                    "raw_z",
                    models.FloatField(
                        blank=True,
                        help_text="Исходная координата Z (ECEF из RINEX)",
                        null=True,
                    ),
                ),
                (
                    "receiver_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер приемника",
                    ),
                ),
                (
                    "antenna_height",
                    models.FloatField(
                        blank=True,
                        help_text="Высота антенны (H) из RINEX",
                        null=True,
                        verbose_name="Высота антенны (H)",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="geoclient.geodeticpoint",
                        verbose_name="Геодезический пункт",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observations",
                        to="geoclient.uploadedrinexfile",
                        verbose_name="Исходный RINEX файл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Наблюдение",
                "verbose_name_plural": "Наблюдения",
                "ordering": ["-timestamp"],
                "unique_together": {("point", "timestamp")},
            },
        ),
    ]
