# Generated by Django 4.2 on 2025-05-24 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedRinexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rinex_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, help_text='Тип файла (o, n, g)', max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Заметки по файлу', null=True)),
            ],
            options={
                'verbose_name': 'Загруженный RINEX файл',
                'verbose_name_plural': 'Загруженные RINEX файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Точка на карте', 'verbose_name_plural': 'Точки на карте'},
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание', null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='raw_x',
            field=models.FloatField(blank=True, help_text='Исходная координата X (ECEF)', null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='raw_y',
            field=models.FloatField(blank=True, help_text='Исходная координата Y (ECEF)', null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='raw_z',
            field=models.FloatField(blank=True, help_text='Исходная координата Z (ECEF)', null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Время наблюдения', null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Координаты точки (WGS84)', srid=4326),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(help_text='Имя точки/маркера', max_length=255),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['location'], name='location_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['timestamp'], name='geoclient_p_timesta_3a6d54_idx'),
        ),
        migrations.AddField(
            model_name='point',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='geoclient.uploadedrinexfile'),
        ),
    ]
