# Generated by Django 5.2.4 on 2025-11-10 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodeticpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='geodeticpoint',
            name='point_type',
            field=models.CharField(choices=[('ggs', 'Пункты гос. геодезической сети'), ('ggs_kurgan', 'Пункты ГГС на курганах'), ('survey', 'Точки съемочной сети'), ('survey_kurgan', 'Точки съемочной сети на курганах'), ('astro', 'Астрономические пункты/Высокоточная сеть'), ('leveling', 'Нивелирная марка/ГНСС'), ('default', 'Неопределенный тип')], default='default', max_length=20, verbose_name='Тип точки'),
        ),
        migrations.AlterField(
            model_name='geodeticpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='stationdirectoryname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='stationdirectoryname',
            name='name',
            field=models.CharField(db_index=True, help_text='Уникальное имя станции из справочника', max_length=255, unique=True, verbose_name='Имя станции в справочнике'),
        ),
        migrations.AlterField(
            model_name='stationdirectoryname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='uploadedrinexfile',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Хэш-сумма SHA-256', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedrinexfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='uploadedrinexfile',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='uploadedrinexfile',
            name='upload_group',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='ID группы связанных файлов', null=True),
        ),
    ]
