# Generated by Django 5.2 on 2025-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoclient", "0002_uploadedrinexfile_alter_point_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="point_type",
            field=models.CharField(
                choices=[
                    ("ggs", "Пункты гос. геодезической сети"),
                    ("ggs_kurgan", "Пункты ГГС на курганах"),
                    ("survey", "Точки съемочной сети"),
                    ("survey_kurgan", "Точки съемочной сети на курганах"),
                    ("astro", "Астрономические пункты"),
                    ("leveling", "Нивелирные марки/реперы"),
                    ("default", "Неопределенный тип"),
                ],
                default="default",
                help_text="Тип точки",
                max_length=20,
            ),
        ),
    ]
