# Generated by Django 5.2 on 2025-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoclient", "0003_point_point_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="point",
            options={
                "ordering": ["id"],
                "verbose_name": "Точка на карте",
                "verbose_name_plural": "Точки на карте",
            },
        ),
        migrations.RemoveField(
            model_name="point",
            name="name",
        ),
        migrations.AddField(
            model_name="point",
            name="antenna_height",
            field=models.FloatField(
                blank=True,
                help_text="Измеренная высота антенны (DELTA H из RINEX)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="receiver_number",
            field=models.CharField(
                blank=True,
                help_text="Номер приемника (REC # из RINEX)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="station_name",
            field=models.CharField(
                blank=True,
                help_text="Присвоенное имя станции/пункта (например, Вахим)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="id",
            field=models.CharField(
                help_text="Идентификатор точки (MARKER NAME из RINEX, например, BAXU)",
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(
                fields=["station_name"], name="geoclient_p_station_94956a_idx"
            ),
        ),
    ]
