# Generated by Django 5.2 on 2025-06-10 05:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoclient", "0004_alter_point_options_remove_point_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationDirectoryName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальное имя станции из справочника (например, Вахим, База_1)",
                        max_length=255,
                        unique=True,
                        verbose_name="Имя станции в справочнике",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления записи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись справочника имен",
                "verbose_name_plural": "Справочник имен станций",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="point",
            new_name="timestamp_idx",
            old_name="geoclient_p_timesta_3a6d54_idx",
        ),
        migrations.RenameIndex(
            model_name="point",
            new_name="station_name_idx",
            old_name="geoclient_p_station_94956a_idx",
        ),
        migrations.AddField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания записи точки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="point",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления записи точки"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="antenna_height",
            field=models.FloatField(
                blank=True,
                help_text="Измеренная высота антенны (компонента H из ANTENNA: DELTA H/E/N в RINEX, в метрах)",
                null=True,
                verbose_name="Высота антенны (H)",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Дополнительное описание или комментарии к точке",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="id",
            field=models.CharField(
                help_text="Идентификатор точки (обычно MARKER NAME из RINEX файла)",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="ID точки (Marker Name)",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Географические координаты точки (долгота, широта в WGS84)",
                srid=4326,
                verbose_name="Местоположение",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="point_type",
            field=models.CharField(
                choices=[
                    ("ggs", "Пункты гос. геодезической сети"),
                    ("ggs_kurgan", "Пункты ГГС на курганах"),
                    ("survey", "Точки съемочной сети"),
                    ("survey_kurgan", "Точки съемочной сети на курганах"),
                    ("astro", "Астрономические пункты"),
                    ("leveling", "Нивелирные марки/реперы"),
                    ("default", "Неопределенный тип"),
                ],
                default="default",
                help_text="Тип геодезического пункта или точки",
                max_length=20,
                verbose_name="Тип точки",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_x",
            field=models.FloatField(
                blank=True, help_text="Исходная координата X (ECEF из RINEX)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_y",
            field=models.FloatField(
                blank=True, help_text="Исходная координата Y (ECEF из RINEX)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_z",
            field=models.FloatField(
                blank=True, help_text="Исходная координата Z (ECEF из RINEX)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="receiver_number",
            field=models.CharField(
                blank=True,
                help_text="Номер приемника (REC # из RINEX)",
                max_length=100,
                null=True,
                verbose_name="Номер приемника",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="geoclient.uploadedrinexfile",
                verbose_name="Исходный RINEX файл",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="station_name",
            field=models.CharField(
                blank=True,
                help_text="Присвоенное пользователем имя станции/пункта",
                max_length=255,
                null=True,
                verbose_name="Присвоенное имя станции",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Время наблюдения или создания записи",
                null=True,
                verbose_name="Время наблюдения",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="file",
            field=models.FileField(upload_to="rinex_files/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="Тип файла (o, n, g, и т.д.)",
                max_length=10,
                null=True,
                verbose_name="Тип файла",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Заметки или комментарии по файлу",
                null=True,
                verbose_name="Заметки",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время загрузки"
            ),
        ),
    ]
