# Generated by Django 5.2 on 2025-06-24 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoclient", "0005_stationdirectoryname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="center_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тип центра"
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="index_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Индекс (номенклатура)",
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="mark_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер марки"
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="network_class",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Класс сети"
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="antenna_height",
            field=models.FloatField(
                blank=True,
                help_text="Высота антенны (H) из RINEX, в метрах",
                null=True,
                verbose_name="Высота антенны (H)",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="point",
            name="id",
            field=models.CharField(
                help_text="ID/Имя точки (Marker Name из RINEX или Имя пункта из каталога)",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="ID/Имя точки",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Местоположение"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="point_type",
            field=models.CharField(
                choices=[
                    ("ggs", "Пункты гос. геодезической сети"),
                    ("ggs_kurgan", "Пункты ГГС на курганах"),
                    ("survey", "Точки съемочной сети"),
                    ("survey_kurgan", "Точки съемочной сети на курганах"),
                    ("astro", "Астрономические пункты"),
                    ("leveling", "Нивелирные марки/реперы"),
                    ("default", "Неопределенный тип"),
                ],
                default="default",
                max_length=20,
                verbose_name="Тип точки",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="receiver_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер приемника"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="station_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Присвоенное имя станции",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время наблюдения"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления записи"
            ),
        ),
    ]
