# Generated by Django 5.2 on 2025-06-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geoclient",
            "0006_point_center_type_point_index_name_point_mark_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="point",
            name="location_idx",
        ),
        migrations.RemoveIndex(
            model_name="point",
            name="timestamp_idx",
        ),
        migrations.RemoveIndex(
            model_name="point",
            name="station_name_idx",
        ),
        migrations.AlterField(
            model_name="point",
            name="antenna_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="point",
            name="id",
            field=models.CharField(
                help_text="ID/Имя точки (Marker Name или Имя пункта)",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="ID/Имя точки",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_z",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="point",
            name="receiver_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="point",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="geoclient.uploadedrinexfile",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stationdirectoryname",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stationdirectoryname",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=255,
                unique=True,
                verbose_name="Имя станции в справочнике",
            ),
        ),
        migrations.AlterField(
            model_name="stationdirectoryname",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="file_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Тип файла"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки"),
        ),
    ]
