# Generated by Django 5.2 on 2025-06-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geoclient",
            "0007_remove_point_location_idx_remove_point_timestamp_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="antenna_height",
            field=models.FloatField(
                blank=True,
                help_text="Высота антенны (H) из RINEX, в метрах",
                null=True,
                verbose_name="Высота антенны (H)",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="id",
            field=models.CharField(
                help_text="ID/Имя точки (Marker Name из RINEX или Имя пункта из каталога)",
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="ID/Имя точки",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_x",
            field=models.FloatField(
                blank=True, help_text="Исходная координата X (ECEF из RINEX)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_y",
            field=models.FloatField(
                blank=True, help_text="Исходная координата Y (ECEF из RINEX)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="raw_z",
            field=models.FloatField(
                blank=True, help_text="Исходная координата Z (ECEF из RINEX)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="receiver_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер приемника"
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="geoclient.uploadedrinexfile",
                verbose_name="Исходный RINEX файл",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления записи"
            ),
        ),
        migrations.AlterField(
            model_name="stationdirectoryname",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AlterField(
            model_name="stationdirectoryname",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Уникальное имя станции из справочника (например, Вахим, База_1)",
                max_length=255,
                unique=True,
                verbose_name="Имя станции в справочнике",
            ),
        ),
        migrations.AlterField(
            model_name="stationdirectoryname",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления записи"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="Тип файла (o, n, g, и т.д.)",
                max_length=10,
                null=True,
                verbose_name="Тип файла",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedrinexfile",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Заметки или комментарии по файлу",
                null=True,
                verbose_name="Заметки",
            ),
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(fields=["location"], name="location_idx"),
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(fields=["timestamp"], name="timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(fields=["station_name"], name="station_name_idx"),
        ),
    ]
