# Generated by Django 5.2 on 2025-07-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geoclient", "0009_uploadedrinexfile_file_hash_geodeticpoint_and_more"),
    ]

    operations = []
